export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION'
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER'
export const LOGOUT = 'LOGOUT'

export const FILE_UPLOAD = 'FILE_UPLOAD'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR'

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS'
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const CLEAR_APP_STATE = 'CLEAR_APP_STATE'

export const ADD_PASSWORD = 'ADD_PASSWORD'
export const ADD_DOWNLOADS = 'ADD_DOWNLOADS'
